# Generated by Django 2.1 on 2020-02-26 11:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200219_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='Senegal', max_length=30),
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='generated_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='suburb',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(default='sn', max_length=6),
        ),
    ]
