# Generated by Django 2.1 on 2020-02-28 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200226_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='building',
            new_name='house_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='person_id',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
