# Generated by Django 2.1 on 2020-02-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200228_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='location_name',
            field=models.CharField(default='Dakar, Senegal', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.CharField(default='Dakar', max_length=30),
        ),
    ]
