# Generated by Django 2.2 on 2020-02-28 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200228_1409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='address',
            name='generated_code',
            field=models.CharField(default='SN-DAK', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='suburb',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
