# Generated by Django 2.2 on 2020-02-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200228_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='generated_code',
            field=models.CharField(default='SN-DAK', max_length=30),
        ),
    ]
