# Generated by Django 2.2 on 2020-03-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200229_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country_code',
        ),
    ]
