# Generated by Django 2.2 on 2020-07-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_address_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=200)),
                ('recording_date', models.DateTimeField(auto_now_add=True)),
                ('duration', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['recording_date'],
            },
        ),
        migrations.RemoveField(
            model_name='address',
            name='house_number',
        ),
    ]
