# Generated by Django 2.2 on 2020-07-19 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200719_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='audio_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Audio'),
        ),
    ]
