# Generated by Django 2.2 on 2020-07-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_address_audio_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='audio_id',
            new_name='audio',
        ),
    ]
