# Generated by Django 2.2 on 2020-08-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200720_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='audio',
        ),
        migrations.AddField(
            model_name='audio',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
    ]
