# Generated by Django 2.2 on 2020-08-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200809_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='generated_code',
            field=models.CharField(default='SN-DAK', max_length=30, unique=True),
        ),
    ]
