# Generated by Django 2.2 on 2021-04-23 02:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_auto_20200810_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='user_adresses', to=settings.AUTH_USER_MODEL),
        ),
    ]
