# Generated by Django 2.2 on 2021-04-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_address_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='users',
        ),
    ]
