# Generated by Django 2.2 on 2021-04-23 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20210423_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='user_audios', to=settings.AUTH_USER_MODEL),
        ),
    ]
